// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asmgutvwjlwqixxaqcrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbWd1dHZ3amx3cWl4eGFxY3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDQ4MDUsImV4cCI6MjA2MzIyMDgwNX0.poX2ioKCXjsHPYJaPBsPiFs_DTqXoQPNWVDlf5v7eVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);